### ISSUE TITLE
Alias and Keystore password are hardcoded

### ISSUE THREAD

**Issue by mikklfr** [llaske/sugarizer-apkbuilder#1]
It would be better for security reasons to leave the user the ability to specify it's own alias/key pair when doing the 
 ``sign`` command.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-apkbuilder/commit/54169fded8cfb30a298520c4ba654b2ff4441330

Three new environment variables are provided: `SUGARIZER_KEYSTOREFILE`, `SUGARIZER_STOREALIAS` and `SUGARIZER_STOREPASS`. See README.md file for more.
