### ISSUE TITLE
Sugarize APK builder README.MD

### ISSUE THREAD

**Issue by rahulkiller104** [llaske/sugarizer-apkbuilder#10]
when I am using this docker command

sudo docker run --rm -it \
	 -v `pwd`/sugarizer:/sugarizer \
	 -v `pwd`/cordova-plugin-sugarizeros:/cordova-plugin-sugarizeros \
	 -v `pwd`:/output \
	 llaske/sugarizer-apkbuilder:latest

I am getting a docker: invalid reference format error.

**Comment by llaske** [comment]
Hmmm. You're right it could happen if your current directory contains characters like white spaces.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-apkbuilder/pull/11
