### ISSUE TITLE
Update Dependency URL for versioncompare in Sugarizer APK Builder

### ISSUE THREAD

**Issue by UtkarshSiddhpura** [llaske/sugarizer-apkbuilder#14]
While building the Sugarizer APK where the dependency URL for `versioncompare` is outdated. 

The current URL 
`https://repo1.maven.org/maven2/io/github/g00fy2/versioncompare/1.3.4/versioncompare-1.3.4.pom`
is no longer valid.  The new URL should be updated to `https://repo1.maven.org/maven2/io/github/g00fy2/versioncompare/1.4.0/versioncompare-1.4.0.pom`

For more details, see the discussion in the [Ionic Forum](https://forum.ionicframework.com/t/build-antroid-app-with-linux-2023-04-and-linux-2023-06-failed-because-it-could-not-resolve-all-artifacts-for-configuration-classpath/234402/2).

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-apkbuilder/commit/6e7bf6c030a2ce5114f6c53e435e091982b40c72
The latest image is upgraded on https://hub.docker.com/layers/llaske/sugarizer-apkbuilder/latest/images/sha256-1c9fc5f9706eb5966e0eb2b0787d613e05d109e4779c5945a9e6502da3d310e9?context=repo
