### ISSUE TITLE
Adding command-line arguments to include/exclude activities

### ISSUE THREAD

**Issue by dhruvmisra** [llaske/sugarizer-apkbuilder#3]
The only way to include/exclude activities from the build is deleting their directories from `/activities` and removing their entries from `activies.json`. During the process of development, this proves to be a cumbersome task as entire directories have to be deleted and restored just for a single build. Alternatively, we can create a separate `sugarizer` folder just for builds but that consumes double the memory.

I would suggest having a command-line argument to include/exclude activities. This can possibly be achieved by inputting a list of activities to be excluded in the command-line and appending the appropriate paths to exclude.android, something like:
```
echo "activities/${activityName}.activity/" >> exclude.android
```
This would exclude the directory from being copied to the build. A similar approach can be implemented to include activities as well by creating include.android file and passing it to rsync as:
```
rsync -av --include-from='include.android' --exclude-from='exclude.android' ../sugarizer/* www
```
This would help create customized builds much quicker and efficiently. What are you thoughts @llaske?

**Comment by llaske** [comment]
Having the possibility to choose the set of activities is clearly a good idea.
Today for example, when I need to build to deploy in Play Store, I need to exclude TurtleJS and Jappy manually (see [here](https://github.com/llaske/sugarizer-apkbuilder/blob/master/src/exclude.android#L10)) for licensing reason.
BTW I'm not sure to understand the way you want to do this. May be adding environment variables like SUGARIZER_KEYSTOREFILE.

**Comment by dhruvmisra** [comment]
Okay I'll try to make my approach clear.
Let's just consider excluding activities for now.

The make_android.sh file uses a command `rsync` to copy the files to the build. ([See here](https://github.com/llaske/sugarizer-apkbuilder/blob/abdd41a274e1be27eb281ad1684e98314971a7b2/src/make_android.sh#L73))
rsync takes the `--exclude-from`  parameter to exclude the directories from being copied. Currently the exclude.android file is passed to it.

Now, we can have a custom command-line argument such as: `exclude-activities`
```
sudo docker run --rm -it \
	 -v `pwd`/sugarizer:/sugarizer \
	 -v `pwd`/cordova-plugin-sugarizeros:/cordova-plugin-sugarizeros \
	 -v `pwd`:/output \
---->    exclude-activities="Abacus,Blockrain,Clock"  <----
	 llaske/sugarizer-apkbuilder:latest
```
Here we'll get the list of activities we want to exclude. Using some bash string and argument manipulations, we can find this argument and extract the list of activity names. Then we can simply append the required paths for those activities to exclude.android file. This way rsync will read all new paths and prevent those directories from being copied.

Here is a sample code I wrote to perform this task:
```shell
for i in $*; do 
  if [[ ${i%%=*} == "exclude-activities" ]]              #Finding the argument
  then 
    activities=${i#*=}                                   #activites=Abacus,Blockrain,Clock
    lastActivity=${activities##*,}                       #lastActivity=Clock
    remaining=true
    echo -e "\n" >> exclude.android
    while [ $remaining == true ]                         #Loop through all activity names
    do
      activity=${activities%%,*}                         #activity=Abacus
      activities=${activities#*,}                        #activities=Blockrain,Clock
      if [ ${#activity} -gt 0 ]                          #Activity name null check
      then
        echo "activities/$activity.activity/" >> exclude.android     #Write path to file
      fi
      if [[ $activity == $lastActivity ]]                #Loop condition
      then
        remaining=false
      fi
    done
  fi
done
```
I hope this makes it clear. We can think of a way to use environment variables in place of the whole list being specified during build command execution. Let me know what you think of this @llaske.

**Comment by llaske** [comment]
Sounds good. But you should also remove activities from the `activities.json` file.
How do you plan to do this?

**Comment by dhruvmisra** [comment]
I would suggest using the `sed` command, which can delete the lines containing a string. 
First of all, we'll create a backup of the original `activities.json` using:
```shel
cp activities.json activities.bak.json
```
Now, we can execute this on each iteration of the while loop:
```shell
sed -i "/${activity}/d" activities.json
```
This deletes the activity entries we wish to exclude, giving us the required activities.json.


To *include* activities, we'll have to use a little different approach utilizing the `grep` command instead to transfer the required activity entries from the original file to the new activities.json.
Initially, we truncate the new activities.json and add just a starting bracket (`[`). Then inside the while loop, we use:
```shell
grep ${activity} activities.bak.json >> activities.json
```
This transfers the required entries. In the end, we append a closing bracket (`]`) to complete the entire file.

**NOTE**
To maintain the correctness of the JSON file, we'll have to remove any extra commas (`,`) from the end of last activity entry. These may be present if we don't select the last activity. We can use the following command to remove this comma if present:
```shell
sed -i "$(( $( wc -l < activities.json) -1 ))s/,$//" activities.json
```

After the build, we can add a command to simply remove the new activities.json and rename the `activities.bak.json` back to `activities.json` to retain our original version.

**Comment by dhruvmisra** [comment]
@llaske I tested my solution by editing the docker image locally and successfully built the APK without any problems. No deletion of any kind required in the `sugarizer` directory. I have added a pull request (#4) with the required changes and testing instructions. Currently only excluding-activities is active. Looking forward to a review.

**Comment by llaske** [comment]
Your solution sounds good. 
One question: I guess the name to specify is the directory name (without `.activity` suffix), not the id or the activity name?
I don't think we need to add the include-activity option. I'm not sure to understand when we could need it.

**Comment by dhruvmisra** [comment]
Yes you're right, the activity name is the string before the suffix `.activity`.
The include-activities can mainly be useful while developing activities and testing them on Android. We can always exclude all other activities but having an option to include only specific ones will be much easier in these scenarios.

**Comment by llaske** [comment]
Usually contributors who work on a new activity update directly the `sugarizer` directory to add the new activity directory and update the `activities.json`. So the activity will be already include when launching APK builder. I'm wrong?

**Comment by dhruvmisra** [comment]
That's correct @llaske, but this would build all activities (a time consuming process) to be able to test our newly created activity. So an option to just include our newly created activity for the build will speed up the process and reduce the build size significantly. 
Actually this is an issue I faced while testing the Fraction Bounce activity on android. I created a separate sugarizer directory just for builds which had only my activity. Therefore I wished for a command-line option to include only this activity while building. This can surely be achieved using the `exclude-activities` option, it's an enhancement. 

Alternatively, we can have a file with all activity names, initially commented out, which can be passed as an environment variable during build. This way, we can un-comment all those activities we wish to exclude from the build. This would remove the need for an `include-activities` option. 
What do you say?

**Comment by llaske** [comment]
The build time is not related to the number of activities, we use a Cordova package so all HTML/JavaScript stuff is just copied in a directory and there is no real compilation on it. Compilation operation is just about Cordova encapsulation and plugins.
The only operation where the time depend of number of activities is `grunt` (minify). It's why it's a good practice to use the `full` option in development mode.
So I don't think include-activities option is need.

**Comment by dhruvmisra** [comment]
Oh I see, I should have used the `full` option. Okay then I think excluding option would satisfy all needs. I'll remove the include-activities code from my Pull Request.
I did observe that grunt would still minify all the activities present in `sugarizer/build`. I wasn't able to find any specific exclude option for it. Maybe creating a new directory for minifying might help. Should I look into that as well?

**Comment by llaske** [comment]
The `full` option is the option to avoid minify for all activities. I don't think it's interesting to exclude minify for only some activities. Is it your idea?
Yes, `grunt` minify all activities and put the result in the `build` directory. This directory is dedicated to that. Not sure to understand why you want to create a new directory?
BTW I'm not fully happy with `grunt` today because it don't support ES6 syntax so I have to manually exclude some activities (see [here](https://github.com/llaske/sugarizer/blob/dev/Gruntfile.js#L18) for example), specifically Vue.js activities. A future enhancement will be to replace `grunt` by something else.

**Comment by dhruvmisra** [comment]
I wanted to exclude minifying of excluded-activities too, as `grunt` currently minifies all activities regardless. A new directory could contain only the the required activities. Although it might create more problems than it solves. I think we can let all activities be minified. I added `rsync` after the  `grunt` command which will copy only the required directories.

**Comment by dhruvmisra** [comment]
@llaske I was looking for alternatives to grunt and stumbled upon [Terser](https://github.com/terser/terser), a fork of `uglify-es` which can minify ES6+ syntax as well. A grunt module [grunt-terser](https://github.com/adascal/grunt-terser) is available with similar configuration as uglify. It seems promising and I'll start working on it after completing this issue.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-apkbuilder/pull/4
