### ISSUE TITLE
activities.json file is removed at the end of build

### ISSUE THREAD

**Issue by llaske** [llaske/sugarizer-apkbuilder#6]
It seems that `activities.json` file in `sugarizer` directory is removed by the script at the end of the build.

It happens only when the `exclude-activities` parameter is NOT used.
I guess it comes from [this line](https://github.com/llaske/sugarizer-apkbuilder/blob/master/src/make_android.sh#L127). The `activities.bak.json` doesn't exist when there is no excluded activities so the previous line remove the `activities.json` file and it's never recovered.

**Comment by dhruvmisra** [comment]
Oh yes, you're right. I should add another check for the `excluded` flag here similar to the [line 146](https://github.com/llaske/sugarizer-apkbuilder/blob/766f7bc8e3746c189635f9a2996e6726970d0e72/src/make_android.sh#L146).
